### ISSUE TITLE
Lab 4 census data question

### ISSUE THREAD

**Issue by jacobtnyoung** [Watts-College/cpp-529-spr-2023#4]
Hi @AntJam-Howell! I am working on lab 4 and running into an issue.

I went through the [lab 4 instructions](https://watts-college.github.io/cpp-529-spr-2023/LABS/lab-04-instructions.html#lab-instructions) and everything replicated on my end.

But, when I changed the city to San Diego I run into an issue. Specifically, the census data used in the lab does not have tract id's that match the geoid's in the population data. Here is what I have:

```
crosswalk <- 
read.csv( "https://raw.githubusercontent.com/DS4PS/cpp-529-master/master/data/cbsatocountycrosswalk.csv",  stringsAsFactors=F, colClasses="character" )

these.msp <- 
  crosswalk$msaname == grep( "^SAN DIEGO", crosswalk$msaname, value=TRUE ) 

these.fips <- crosswalk$fipscounty[ these.msp ]
these.fips <- na.omit( these.fips )

state.fips <- substr( these.fips, 1, 2 )
county.fips <- substr( these.fips, 3, 5 )

sd.pop <- get_acs( 
  geography = "tract", 
  variables = "B01003_001", 
  state = state.fips, 
  county = county.fips,
  geometry = TRUE ) %>% 
  select( GEOID, estimate ) %>%
  rename( POP=estimate )
```

These are fine up to here. I get the population data for the tracts in San Diego.

The issue starts when I try to merge the `sd.pop` object with the census data from the lab tutorial.

```
# Get the census data
URL <- "https://github.com/DS4PS/cpp-529-master/raw/master/data/ltdb_std_2010_sample.rds"

census.dat <- readRDS( gzcon( url( URL ) ) )

sdd <- merge( sd.pop, census.dat, by.x="GEOID", by.y="tractid" )

```

The last statement executes, but the object is missing data. It looks like the `tractid` in the `census.dat` object does not contain the tracts in the `sd.pop` object:

```
table(sd.pop$GEOID %in% census.dat$tractid)
```

Am I using the right census data? If I missed a step about us creating a census data object, let me know. I just thought we were supposed to use the one from the lab 4 instructions page.

Let me know at your convenience! Thanks! :)

**Comment by AntJam-Howell** [comment]
@jacobtnyoung Nice question. Its a bit tricky because the state fips for California is labeled as 06 in when downloading directly using `get_acs` where it is labeled as a 6 in the tractid variable of census.dat.  In other words the GEOID string for San Diego includes an extra digit, e.g. 06073010501 whereas the corresponding  tractid string does not, e.g. 6073010501. 

assuming the san diego data is labeled as sanD.pop, the following code should truncate the string by removing the first string element (0) and can then find San Diego matches in the census.dat:
sanD.pop$GEOID<-sub('.', '', sanD.pop$GEOID)

best

**Comment by jacobtnyoung** [comment]
Will give it a shot! Thanks!

**Comment by jacobtnyoung** [comment]
That did the trick. Thanks.
